export const sounds = {
  AMBIENT_STRUCTURE_ALCHEMIST: `${process.env.PUBLIC_URL}/sound/structures/alchemist.ogg`,
  AMBIENT_STRUCTURE_SMITH: `${process.env.PUBLIC_URL}/sound/structures/smith.ogg`,
  AMBIENT_STRUCTURE_TAVERN: `${process.env.PUBLIC_URL}/sound/structures/tavern.ogg`,
  AMBIENT_STRUCTURE_WAREHOUSE: `${process.env.PUBLIC_URL}/sound/structures/warehouse.ogg`,
  MUSIC_COMBAT: `${process.env.PUBLIC_URL}/sound/music/TribalHut.ogg`,
  MUSIC_TOWN: `${process.env.PUBLIC_URL}/sound/music/Soliloquy.mp3`,
  MUSIC_VIOLETTES: `${process.env.PUBLIC_URL}/sound/music/ViolettesElficSongForLamentandHope.ogg`,
  MUSIC_WORLD: `${process.env.PUBLIC_URL}/sound/music/TheLoomingBattle.ogg`,
  UI_BUTTON_CLICK: `${process.env.PUBLIC_URL}/sound/ui/button-click.ogg`,
  UI_EQUIP: `${process.env.PUBLIC_URL}/ssound/ui/equip.mp3`,
  UI_ERROR: `${process.env.PUBLIC_URL}/sound/ui/error.ogg`,
  UI_LEVEL_UP: `${process.env.PUBLIC_URL}/sound/ui/level-up.ogg`,
  UI_TOAST: `${process.env.PUBLIC_URL}/sound/ui/toast.ogg`,
  SCENE_BOW: [`${process.env.PUBLIC_URL}/sound/scene/bow-01.mp3`, `${process.env.PUBLIC_URL}/sound/scene/bow-02.mp3`],
  SCENE_CROSSBOW: [
    `${process.env.PUBLIC_URL}/sound/scene/crossbow-01.mp3`, 
    `${process.env.PUBLIC_URL}/sound/scene/crossbow-02.mp3`, 
    `${process.env.PUBLIC_URL}/sound/scene/crossbow-03.mp3`, 
    `${process.env.PUBLIC_URL}/sound/scene/crossbow-04.mp3`,
  ],
  SCENE_DAGGER_SWISH: `${process.env.PUBLIC_URL}/sound/scene/dagger-swish.ogg`,
  SCENE_DRINKING: `${process.env.PUBLIC_URL}/sound/scene/drinking.ogg`,
  SCENE_DOOR_OPEN: `${process.env.PUBLIC_URL}/sound/scene/door.ogg`,
  SCENE_MELEE_HIT: [
    `${process.env.PUBLIC_URL}/sound/scene/melee-hit-01.mp3`, 
    `${process.env.PUBLIC_URL}/sound/scene/melee-hit-02.mp3`, 
    `${process.env.PUBLIC_URL}/sound/scene/melee-hit-03.mp3`,
  ],
  SCENE_METAL_BASH: [
    `${process.env.PUBLIC_URL}/sound/scene/metal-bash-01.mp3`, 
    `${process.env.PUBLIC_URL}/sound/scene/metal-bash-02.mp3`, 
    `${process.env.PUBLIC_URL}/sound/scene/metal-bash-03.mp3`,
  ],
  SCENE_PARRY: [
    `${process.env.PUBLIC_URL}/sound/scene/parry-01.ogg`, 
    `${process.env.PUBLIC_URL}/sound/scene/parry-02.ogg`,
  ],
  SCENE_SHIELD_BASH: `${process.env.PUBLIC_URL}/sound/scene/shield-bash-impact.mp3`,
  SCENE_SWISH: [
    `${process.env.PUBLIC_URL}/sound/scene/swish-01.mp3`, 
    `${process.env.PUBLIC_URL}/sound/scene/swish-02.mp3`, 
    `${process.env.PUBLIC_URL}/sound/scene/swish-03.mp3`, 
    `${process.env.PUBLIC_URL}/sound/scene/swish-04.mp3`,
  ],
  SCENE_SWORD_HIT_FLESH: [
    `${process.env.PUBLIC_URL}/sound/scene/sword-hit-flesh-01.mp3`, 
    `${process.env.PUBLIC_URL}/sound/scene/sword-hit-flesh-02.mp3`, 
    `${process.env.PUBLIC_URL}/sound/scene/sword-hit-flesh-03.mp3`, 
    `${process.env.PUBLIC_URL}/sound/scene/sword-hit-flesh-04.mp3`,
  ],
};