// not used. see manifets/sounds.ts
export const sounds = {
  AMBIENT_STRUCTURE_ALCHEMIST: `sound/structures/alchemist.ogg`,
  AMBIENT_STRUCTURE_SMITH: `sound/structures/smith.ogg`,
  AMBIENT_STRUCTURE_TAVERN: `sound/structures/tavern.ogg`,
  AMBIENT_STRUCTURE_WAREHOUSE: `sound/structures/warehouse.ogg`,
  MUSIC_COMBAT: `sound/music/TribalHut.ogg`,
  MUSIC_TOWN: `sound/music/Soliloquy.mp3`,
  MUSIC_VIOLETTES: `sound/music/ViolettesElficSongForLamentandHope.ogg`,
  MUSIC_WORLD: `sound/music/TheLoomingBattle.ogg`,
  UI_BUTTON_CLICK: `sound/ui/button-click.ogg`,
  UI_EQUIP: `ssound/ui/equip.mp3`,
  UI_ERROR: `sound/ui/error.ogg`,
  UI_LEVEL_UP: `sound/ui/level-up.ogg`,
  UI_TOAST: `sound/ui/toast.ogg`,
  SCENE_BOW: [`sound/scene/bow-01.mp3`, `sound/scene/bow-02.mp3`],
  SCENE_CROSSBOW: [
    `sound/scene/crossbow-01.mp3`,
    `sound/scene/crossbow-02.mp3`,
    `sound/scene/crossbow-03.mp3`,
    `sound/scene/crossbow-04.mp3`,
  ],
  SCENE_DAGGER_SWISH: `sound/scene/dagger-swish.ogg`,
  SCENE_DRINKING: `sound/scene/drinking.ogg`,
  SCENE_DOOR_OPEN: `sound/scene/door.ogg`,
  SCENE_MELEE_HIT: [
    `sound/scene/melee-hit-01.mp3`,
    `sound/scene/melee-hit-02.mp3`,
    `sound/scene/melee-hit-03.mp3`,
  ],
  SCENE_METAL_BASH: [
    `sound/scene/metal-bash-01.mp3`,
    `sound/scene/metal-bash-02.mp3`,
    `sound/scene/metal-bash-03.mp3`,
  ],
  SCENE_PARRY: [
    `sound/scene/parry-01.ogg`,
    `sound/scene/parry-02.ogg`,
  ],
  SCENE_SHIELD_BASH: `sound/scene/shield-bash-impact.mp3`,
  SCENE_SWISH: [
    `sound/scene/swish-01.mp3`,
    `sound/scene/swish-02.mp3`,
    `sound/scene/swish-03.mp3`,
    `sound/scene/swish-04.mp3`,
  ],
  SCENE_SWORD_HIT_FLESH: [
    `sound/scene/sword-hit-flesh-01.mp3`,
    `sound/scene/sword-hit-flesh-02.mp3`,
    `sound/scene/sword-hit-flesh-03.mp3`,
    `sound/scene/sword-hit-flesh-04.mp3`,
  ],
}
