name: Run tests manually-2

on:
  workflow_dispatch:
    inputs:
      arrowword:
        type: boolean
        required: false

      sudoku:
        type: boolean
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set selected tags variable
        id: set-tags
        run: |
          TAGS=""
          INPUTS=$(echo "${{ toJson(github.event.inputs) }}" | jq -r 'keys[]')

          for INPUT in $INPUTS; do
            VALUE=$(echo "${{ toJson(github.event.inputs) }}" | jq -r --arg INPUT "$INPUT" '.[$INPUT]')
            if [ "$VALUE" == "true" ]; then
              if [ -z "$TAGS" ]; then
                TAGS="$INPUT"
              else
                TAGS="$TAGS|$INPUT"
              fi
            fi
          done

          echo "TAGS=$TAGS" >> $GITHUB_ENV

      - name: Use the selected tags variable
        run: echo "Selected tags ${{ steps.set-tags.outputs.tags }}"
